/**
 * DETAIL PALS V2 — Database Types
 * ==================================
 * File: src/lib/supabase/database.types.ts
 *
 * TypeScript types matching the PostgreSQL schema exactly.
 * In a real project these are generated by `supabase gen types typescript`.
 * Structure follows Supabase's generated format so tooling works correctly.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'admin' | 'staff'
export type BookingStatus = 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled'
export type ServiceTierDB = 'essential' | 'signature' | 'concours'
export type VehicleTypeDB = 'sedan' | 'suv' | 'truck' | 'van' | 'luxury'
export type VehicleConditionDB = 'light' | 'moderate' | 'heavy'
export type EmailTemplate = 'booking-confirmation' | 'staff-notification' | 'contact-reply' | 'booking-reminder'
export type ContactStatus = 'new' | 'responded' | 'archived'
export type ReviewPlatform = 'google' | 'direct' | 'facebook' | 'trustpilot'

export interface Database {
  public: {
    Tables: {

      // ── Staff user profiles ──────────────────────────────────
      profiles: {
        Row: {
          id:         string       // uuid, FK auth.users
          full_name:  string
          role:       UserRole
          avatar_url: string | null
          is_active:  boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id:         string
          full_name:  string
          role?:      UserRole      // defaults to 'staff'
          avatar_url?: string | null
          is_active?:  boolean      // defaults to true
          created_at?: string
          updated_at?: string
        }
        Update: {
          full_name?:  string
          role?:       UserRole
          avatar_url?: string | null
          is_active?:  boolean
          updated_at?: string
        }
      }

      // ── Customer records ─────────────────────────────────────
      customers: {
        Row: {
          id:              string       // uuid
          name:            string
          email:           string | null
          phone:           string
          vehicle_default: string | null // e.g. "BMW M3 2023"
          notes:           string | null
          booking_count:   number       // computed by trigger
          total_spend:     number       // computed by trigger
          created_at:      string
          updated_at:      string
        }
        Insert: {
          id?:              string
          name:             string
          email?:           string | null
          phone:            string
          vehicle_default?: string | null
          notes?:           string | null
          created_at?:      string
          updated_at?:      string
        }
        Update: {
          name?:            string
          email?:           string | null
          phone?:           string
          vehicle_default?: string | null
          notes?:           string | null
          updated_at?:      string
        }
      }

      // ── Service tiers ────────────────────────────────────────
      services: {
        Row: {
          id:            string         // uuid
          tier:          ServiceTierDB
          name:          string
          tagline:       string
          description:   string
          base_price:    number
          duration_min:  number         // hours
          duration_max:  number         // hours
          includes:      string[]
          badge:         string | null
          is_active:     boolean
          display_order: number
          created_at:    string
          updated_at:    string
        }
        Insert: {
          id?:           string
          tier:          ServiceTierDB
          name:          string
          tagline:       string
          description:   string
          base_price:    number
          duration_min:  number
          duration_max:  number
          includes?:     string[]
          badge?:        string | null
          is_active?:    boolean
          display_order?: number
          created_at?:   string
          updated_at?:   string
        }
        Update: {
          name?:         string
          tagline?:      string
          description?:  string
          base_price?:   number
          duration_min?: number
          duration_max?: number
          includes?:     string[]
          badge?:        string | null
          is_active?:    boolean
          display_order?: number
          updated_at?:   string
        }
      }

      // ── Add-on services ──────────────────────────────────────
      add_ons: {
        Row: {
          id:          string
          name:        string
          description: string
          price:       number
          is_active:   boolean
          created_at:  string
          updated_at:  string
        }
        Insert: {
          id?:         string
          name:        string
          description: string
          price:       number
          is_active?:  boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?:        string
          description?: string
          price?:       number
          is_active?:   boolean
          updated_at?:  string
        }
      }

      // ── Pricing configuration ────────────────────────────────
      pricing_config: {
        Row: {
          id:                   string  // always single row: 'singleton'
          vehicle_multipliers:  Json    // { sedan:1.0, suv:1.2, truck:1.25, van:1.3, luxury:1.4 }
          condition_multipliers: Json   // { light:1.0, moderate:1.15, heavy:1.35 }
          updated_at:           string
          updated_by:           string | null  // profiles.id
        }
        Insert: {
          id?:                   string
          vehicle_multipliers?:  Json
          condition_multipliers?: Json
          updated_at?:           string
          updated_by?:           string | null
        }
        Update: {
          vehicle_multipliers?:  Json
          condition_multipliers?: Json
          updated_at?:           string
          updated_by?:           string | null
        }
      }

      // ── Bookings ─────────────────────────────────────────────
      bookings: {
        Row: {
          id:              string
          ref:             string           // DP-XXXXXX
          customer_id:     string           // FK customers
          service_id:      string           // FK services
          vehicle_type:    VehicleTypeDB
          vehicle_make:    string
          vehicle_model:   string
          vehicle_year:    number | null
          condition:       VehicleConditionDB
          add_on_ids:      string[]          // FK add_ons[]
          quoted_price:    number
          final_price:     number | null
          status:          BookingStatus
          booking_date:    string            // ISO date
          time_slot:       string            // e.g. "09:00"
          staff_id:        string | null     // FK profiles
          notes:           string | null
          internal_notes:  string | null
          created_at:      string
          updated_at:      string
        }
        Insert: {
          id?:             string
          ref?:            string
          customer_id:     string
          service_id:      string
          vehicle_type:    VehicleTypeDB
          vehicle_make:    string
          vehicle_model:   string
          vehicle_year?:   number | null
          condition:       VehicleConditionDB
          add_on_ids?:     string[]
          quoted_price:    number
          final_price?:    number | null
          status?:         BookingStatus
          booking_date:    string
          time_slot:       string
          staff_id?:       string | null
          notes?:          string | null
          internal_notes?: string | null
          created_at?:     string
          updated_at?:     string
        }
        Update: {
          final_price?:    number | null
          status?:         BookingStatus
          staff_id?:       string | null
          notes?:          string | null
          internal_notes?: string | null
          updated_at?:     string
        }
      }

      // ── Booking status audit log ─────────────────────────────
      booking_status_log: {
        Row: {
          id:          string
          booking_id:  string            // FK bookings
          from_status: BookingStatus | null
          to_status:   BookingStatus
          changed_by:  string | null     // FK profiles (null = system)
          note:        string | null
          changed_at:  string
        }
        Insert: {
          id?:          string
          booking_id:   string
          from_status?: BookingStatus | null
          to_status:    BookingStatus
          changed_by?:  string | null
          note?:        string | null
          changed_at?:  string
        }
        Update: never  // audit log is immutable
      }

      // ── Availability slots ───────────────────────────────────
      availability_slots: {
        Row: {
          id:              string
          slot_date:       string    // ISO date
          time_slot:       string    // "09:00"
          capacity:        number    // default 1
          bookings_count:  number    // maintained by trigger
          is_blocked:      boolean
          blocked_reason:  string | null
          created_at:      string
        }
        Insert: {
          id?:             string
          slot_date:       string
          time_slot:       string
          capacity?:       number
          bookings_count?: number
          is_blocked?:     boolean
          blocked_reason?: string | null
          created_at?:     string
        }
        Update: {
          capacity?:       number
          is_blocked?:     boolean
          blocked_reason?: string | null
        }
      }

      // ── Gallery ──────────────────────────────────────────────
      gallery: {
        Row: {
          id:                  string
          before_url:          string     // public CDN URL
          after_url:           string
          before_storage_path: string     // Supabase Storage path
          after_storage_path:  string
          vehicle:             string
          service_id:          string | null  // FK services
          hours:               number
          tags:                string[]
          caption:             string | null
          is_published:        boolean
          display_order:       number
          created_at:          string
          updated_at:          string
        }
        Insert: {
          id?:                  string
          before_url:           string
          after_url:            string
          before_storage_path:  string
          after_storage_path:   string
          vehicle:              string
          service_id?:          string | null
          hours?:               number
          tags?:                string[]
          caption?:             string | null
          is_published?:        boolean
          display_order?:       number
          created_at?:          string
          updated_at?:          string
        }
        Update: {
          vehicle?:        string
          service_id?:     string | null
          hours?:          number
          tags?:           string[]
          caption?:        string | null
          is_published?:   boolean
          display_order?:  number
          updated_at?:     string
        }
      }

      // ── Testimonials ─────────────────────────────────────────
      testimonials: {
        Row: {
          id:           string
          booking_id:   string | null    // FK bookings (optional link)
          author_name:  string
          vehicle:      string
          service_tier: ServiceTierDB | null
          rating:       number           // 1-5
          quote:        string
          review_date:  string
          is_published: boolean
          platform:     ReviewPlatform
          created_at:   string
          updated_at:   string
        }
        Insert: {
          id?:           string
          booking_id?:   string | null
          author_name:   string
          vehicle:       string
          service_tier?: ServiceTierDB | null
          rating:        number
          quote:         string
          review_date:   string
          is_published?: boolean
          platform?:     ReviewPlatform
          created_at?:   string
          updated_at?:   string
        }
        Update: {
          author_name?:  string
          vehicle?:      string
          service_tier?: ServiceTierDB | null
          rating?:       number
          quote?:        string
          review_date?:  string
          is_published?: boolean
          platform?:     ReviewPlatform
          updated_at?:   string
        }
      }

      // ── Contact form submissions ─────────────────────────────
      contacts: {
        Row: {
          id:          string
          name:        string
          email:       string | null
          phone:       string | null
          vehicle:     string | null
          message:     string
          source:      'contact-form' | 'booking-enquiry'
          status:      ContactStatus
          customer_id: string | null  // FK customers (linked if email matches)
          created_at:  string
          updated_at:  string
        }
        Insert: {
          id?:          string
          name:         string
          email?:       string | null
          phone?:       string | null
          vehicle?:     string | null
          message:      string
          source?:      'contact-form' | 'booking-enquiry'
          status?:      ContactStatus
          customer_id?: string | null
          created_at?:  string
          updated_at?:  string
        }
        Update: {
          status?:      ContactStatus
          customer_id?: string | null
          updated_at?:  string
        }
      }

      // ── Market rates cache ───────────────────────────────────
      market_rates_cache: {
        Row: {
          id:           string
          tier:         ServiceTierDB
          vehicle_type: VehicleTypeDB
          min_price:    number
          max_price:    number
          last_updated: string
          source:       string
        }
        Insert: {
          id?:          string
          tier:         ServiceTierDB
          vehicle_type: VehicleTypeDB
          min_price:    number
          max_price:    number
          last_updated?: string
          source?:       string
        }
        Update: {
          min_price?:    number
          max_price?:    number
          last_updated?: string
          source?:       string
        }
      }

      // ── Email log ────────────────────────────────────────────
      email_log: {
        Row: {
          id:          string
          to_email:    string
          template:    EmailTemplate
          booking_id:  string | null
          resend_id:   string | null
          status:      'sent' | 'failed' | 'bounced'
          error_msg:   string | null
          sent_at:     string
        }
        Insert: {
          id?:         string
          to_email:    string
          template:    EmailTemplate
          booking_id?: string | null
          resend_id?:  string | null
          status?:     'sent' | 'failed' | 'bounced'
          error_msg?:  string | null
          sent_at?:    string
        }
        Update: {
          status?:    'sent' | 'failed' | 'bounced'
          error_msg?: string | null
        }
      }

    }

    Views: {
      // View: bookings joined with customer and service for convenience
      bookings_view: {
        Row: {
          id:            string
          ref:           string
          status:        BookingStatus
          booking_date:  string
          time_slot:     string
          quoted_price:  number
          final_price:   number | null
          customer_name: string
          customer_phone: string
          vehicle_type:  VehicleTypeDB
          vehicle_make:  string
          vehicle_model: string
          service_name:  string
          service_tier:  ServiceTierDB
          staff_name:    string | null
          created_at:    string
        }
      }
    }

    Functions: {
      generate_booking_ref: {
        Args: Record<string, never>
        Returns: string
      }
    }

    Enums: {
      user_role:         { Values: UserRole }
      booking_status:    { Values: BookingStatus }
      service_tier:      { Values: ServiceTierDB }
      vehicle_type:      { Values: VehicleTypeDB }
      vehicle_condition: { Values: VehicleConditionDB }
      review_platform:   { Values: ReviewPlatform }
      contact_status:    { Values: ContactStatus }
      email_template:    { Values: EmailTemplate }
    }
  }
}

// ─── Convenience row types ───────────────────────────────────

export type Profile           = Database['public']['Tables']['profiles']['Row']
export type Customer          = Database['public']['Tables']['customers']['Row']
export type ServiceRow        = Database['public']['Tables']['services']['Row']
export type AddOnRow          = Database['public']['Tables']['add_ons']['Row']
export type PricingConfig     = Database['public']['Tables']['pricing_config']['Row']
export type Booking           = Database['public']['Tables']['bookings']['Row']
export type BookingStatusLog  = Database['public']['Tables']['booking_status_log']['Row']
export type AvailabilitySlot  = Database['public']['Tables']['availability_slots']['Row']
export type GalleryRow        = Database['public']['Tables']['gallery']['Row']
export type TestimonialRow    = Database['public']['Tables']['testimonials']['Row']
export type Contact           = Database['public']['Tables']['contacts']['Row']
export type MarketRate        = Database['public']['Tables']['market_rates_cache']['Row']
export type EmailLog          = Database['public']['Tables']['email_log']['Row']
export type BookingView       = Database['public']['Views']['bookings_view']['Row']

// Insert types
export type BookingInsert     = Database['public']['Tables']['bookings']['Insert']
export type CustomerInsert    = Database['public']['Tables']['customers']['Insert']
export type ContactInsert     = Database['public']['Tables']['contacts']['Insert']

// Auth helpers
export interface AuthUser {
  id:        string
  email:     string | undefined
  role:      UserRole
  full_name: string
}
